/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "k8s-workshop"
include(
        ":module:lib:k8s-workshop-avro-schemes",
        ":module:lib:k8s-workshop-messaging-starter",
        ":module:app:k8s-workshop-data-generator",
        ":module:app:k8s-workshop-listener"
)