spring:
  profiles:
    active: dev
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
        bindings:
          sensorDataConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true

      bindings:
        sensorDataConsumer-in-0:
          destination: ${app.messaging.topics.SENSOR_DATA.topic-name}
          group: sensor-data-listener

app:
  messaging:
    serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    scheme-registry-url: http://localhost:8081
    topics:
      SENSOR_DATA:
        output-binding-name: sensorDataConsumer-in-0
        topic-name: sensor-data