name: Check Branch

on:
  push:
    branches:
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Build
        run: CI=true ./gradlew clean assemble
      - name: Test
        run: CI=true ./gradlew test
      - name: Integration Test
        run: CI=true ./gradlew integrationTest
